// Generated by ReScript, PLEASE EDIT WITH CARE


function make_footer(footer) {
  return "\n  <table style=\"font-family: arial; margin-left: 20px;\">\n    <tbody>\n      <tr>\n        <td style=\"padding-right: 20px;\">\n          <img\n            style=\"width: 110px; height: 110px;\"\n            src=\"" + footer.image + "\"\n          />\n        </td>\n        <td>\n          <h2\n            style=\"\n              margin: 0px;\n              font-size: 18px;\n              margin-top: 1px;\n            \"\n          >\n            " + footer.name + "\n          </h2>\n          <p style=\"\n            margin: 0px;\n            line-height: 30px;\n            font-size: 14px;\n            font-weight: lighter;\n          \">\n            " + footer.description + "\n          </p>\n          <p style=\"\n            color: #4565AF;\n            margin: 0px;\n            font-size: 14px;\n            font-weight: lighter;\n          \">\n            " + footer.phone + "\n          </p>\n        </td>\n      </tr>\n      <tr/>\n        <td style=\"\n            height: 40px;\n            display: flex;\n            align-items: center;\n        \">\n          <img\n            style=\"\n              position: relative;\n              left: 4px;\n              width: 90px;\n              margin: auto;\n              display: block;\n            \"\n            src=\"" + footer.logo + "\"\n          />\n        </td>\n\n        <td style=\"text-align: center;\">\n          <p\n            style=\"\n              margin: 0px;\n              line-height: 40px;\n              font-size: 14px;\n              font-weight: lighter;\n            \"\n          >\n            <span style=\"color: #4cbf94;\">" + footer.highlightText + "</span>\n            " + footer.extraText + "\n          </p>\n        </td>\n\n      </tr>\n    </tbody>\n  </table>\n";
}

export {
  make_footer ,
}
/* No side effect */
